name: Deploy Dhall Documentation to GitHub Pages

on:
  # Trigger on pushes to main or master branch
  push:
    branches: [ main, master ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-docs:
    uses: nikita-volkov/deploy-dhall-docs-to-github-pages.github-actions-workflow/.github/workflows/main.yaml@master
    with:
      input: src
      package-name: typeclasses
    secrets: inherit
